#!/bin/sh

[ -z "$1" ] && echo "usage: $0 file" 1>&2 && exit 1

TEMPLATEDIR="$HOME/.local/share/dwmtemplate"

IFS='
'
for l in $(cat "$TEMPLATEDIR/$1"); do
	echo $l | sed 's/\(^\|[^\\]\)\#.*//' | xargs xdotool
done
