#!/bin/sh

[ -z "$1" ] && echo "usage: $0 file" 1>&2 && exit 1

TEMPLATEDIR="$HOME/.local/share/dwmtemplate"

while getopts "d:" opt; do
	case $opt in
		d) TEMPLATEDIR=$OPTARG;;
	esac
done
shift $((OPTIND-1))

IFS='
'
for l in $(cat "$TEMPLATEDIR/$1"); do
	echo $l | sed 's/\(^\|[^\\]\)\#.*//' | envsubst | xargs xdotool
done
